#!/usr/bin/env python2

import sys
import matplotlib.pyplot as plt
import numpy as np

def parse():
    n = int(raw_input())

    x = np.zeros(n)
    y = np.zeros(n)
    s = np.zeros(n, dtype=np.int)
    t = np.zeros(n, dtype=np.int)
    ok = np.zeros((n,n), dtype=np.int)

    print "n = ", n
    
    for i in range(0, n):
        x[i], y[i] = map(float, raw_input().split())
        
    for i in range(0, n):
        s[i], t[i] = map(int, raw_input().split())
        if ok[s[i], t[i]] == 1 or ok[t[i], s[i]]:
            print "warning ", s[i], s[j], " chosen twice"
        else:
            ok[s[i], t[i]] = 1
            ok[t[i], s[i]] = 1

    return n, x, y, s, t

if __name__ == "__main__":
    n, x, y, s, t = parse()
    plt.plot(x, y, "ro")

    if len(sys.argv) >= 2:
        for i in range(0, n):
            plt.text(x[i]+2, y[i]+2, str(i))

            
    for i in range(0, n):
        plt.plot( [x[s[i]], x[t[i]] ], [y[s[i]], y[t[i]] ])
#        plt.quiver( [ x[s[i]] ], [ y[s[i]] ],
#                    [ x[t[i]] - x[s[i]]], [y[t[i]] - y[s[i]]],
#                    scale_units='xy', angles='xy', scale=1)
        
    plt.show()
